name: Publish Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build schema image
        run: |
          docker build \
            --no-cache \
            --tag ghcr.io/spaceapi/schema \
            --label "org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            .
      - name: Publish schema image
        run: |
          docker push ghcr.io/spaceapi/schema:latest
