name: Validate schema

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate-json-schema:
    name: v${{ matrix.schema }} schema
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schema: [12, 13, 14, 15-draft]
    steps:
      - uses: actions/checkout@v4
      - name: Install validator
        run: npm install ajv-cli@3.1.0
      - name: Download JSON meta-schema
        run: wget -O meta-schema https://json-schema.org/draft-07/schema
      - name: Validate schema file against meta-schema
        run: npx ajv validate -s meta-schema -d "${{ matrix.schema }}.json" --add-used-schema false --errors=text
